"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { clientFetch } from "@/shared/api/client";

export type VideoRendition = {
  id: string;
  protocol: string;
  label: string;
  width?: number;
  height?: number;
  bitrateKbps?: number;
  storageKey: string;
};

export type VideoCaption = {
  id: string;
  language: string;
  kind: string;
  storageKey: string;
  autoGenerated: boolean;
};

export type VideoManifest = {
  videoId: string;
  protocol: string;
  status: string;
  renditions: VideoRendition[];
  captions: VideoCaption[];
};

export type VideoProgress = {
  videoId: string;
  userId: string;
  positionSeconds: number;
  durationSeconds?: number;
  playbackRate: number;
  completed: boolean;
};

export type PlaybackUrl = { videoId: string; url: string; expiresAt: string };

function shouldRetryMediaQuery(failureCount: number, error: Error) {
  const status = (error as Error & { status?: number }).status;
  if (status && status >= 400 && status < 500) return false;
  return failureCount < 2;
}

export function useVideoManifest(videoId: string, protocol = "HLS") {
  return useQuery({
    queryKey: ["video-manifest", videoId, protocol],
    queryFn: () => clientFetch<VideoManifest>(`/v1/media/videos/${videoId}/manifest?protocol=${protocol}`),
    enabled: Boolean(videoId),
    retry: shouldRetryMediaQuery
  });
}

export function usePlaybackUrl(videoId: string, protocol = "hls") {
  return useQuery({
    queryKey: ["video-playback-url", videoId, protocol],
    queryFn: () => clientFetch<PlaybackUrl>(`/v1/media/videos/${videoId}/playback-url?protocol=${protocol}`),
    enabled: Boolean(videoId),
    retry: shouldRetryMediaQuery
  });
}

export function useVideoProgress(videoId: string, userId: string) {
  return useQuery({
    queryKey: ["video-progress", videoId, userId],
    queryFn: () => clientFetch<VideoProgress>(`/v1/media/videos/${videoId}/progress?userId=${userId}`),
    enabled: Boolean(videoId && userId),
    retry: shouldRetryMediaQuery
  });
}

/**
 * Persist the resume position. Call this on a throttled interval (e.g. every 10s)
 * and on pause/unload so the learner can resume where they left off.
 */
export function useSaveProgress(videoId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (input: { userId: string; positionSeconds: number; durationSeconds?: number; playbackRate?: number; completed?: boolean }) =>
      clientFetch<VideoProgress>(`/v1/media/videos/${videoId}/progress`, { method: "PUT", body: input }),
    onSuccess: (_data, variables) => {
      qc.invalidateQueries({ queryKey: ["video-progress", videoId, variables.userId] });
    }
  });
}
