server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-auth
          uri: ${IDENTITY_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RewritePath=/api/v1/(?<segment>auth/.*), /$\{segment}
        - id: identity-profile
          uri: ${IDENTITY_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/users/me
          filters:
            - RewritePath=/api/v1/(?<segment>users/me), /$\{segment}
        - id: identity-backoffice-users
          uri: ${IDENTITY_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/admin/v1/users,/api/admin/v1/users/**
          filters:
            - RewritePath=/api/admin/v1/users(?<segment>/?.*), /backoffice/users$\{segment}
        - id: identity-authz
          uri: ${IDENTITY_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=/api/internal/v1/authz/check
          filters:
            - SetPath=/internal/authz/check

training:
  jwt:
    secret: ${COURSEFLOW_JWT_SECRET:courseflow-training-jwt-secret-32-bytes}
    issuer: ${JWT_ISSUER:courseflow-training-identity}

management:
  endpoints:
    web:
      exposure:
        include: health,info
