package edu.courseflow.media.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(name = "video_captions")
public class VideoCaption {

    @Id
    private UUID id;

    @Column(name = "video_id", nullable = false)
    private UUID videoId;

    @Column(nullable = false, length = 16)
    private String language;

    @Column(nullable = false, length = 20)
    private String kind = "SUBTITLE";

    @Column(name = "storage_key", nullable = false, length = 512)
    private String storageKey;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    protected VideoCaption() {
    }

    public UUID getId() { return id; }
    public String getLanguage() { return language; }
    public String getKind() { return kind; }
    public String getStorageKey() { return storageKey; }
    public boolean isAutoGenerated() { return autoGenerated; }
}
