global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: courseflow-api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: courseflow-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - discovery-service:8080
          - access-control-service:8080
          - user-management-service:8080
          - course-service:8080
          - enrollment-service:8080
          - assignment-service:8080
          - notification-service:8080
          - media-service:8080
          - search-service:8080
          - gradebook-service:8080
          - quiz-service:8080
          - outbox-relay:8080
          - chat-service:8080
