package edu.courseflow.media.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import java.time.Instant;
import java.util.List;

public final class VideoDtos {

    private VideoDtos() {
    }

    public record VideoAssetDto(
            String id,
            String mediaAssetId,
            String courseId,
            String title,
            String sourceStorageKey,
            Integer durationSeconds,
            String status,
            Instant createdAt,
            List<VideoRenditionDto> renditions,
            List<VideoCaptionDto> captions
    ) {
    }

    public record VideoRenditionDto(
            String id,
            String protocol,
            String label,
            Integer width,
            Integer height,
            Integer bitrateKbps,
            String storageKey
    ) {
    }

    public record VideoCaptionDto(
            String id,
            String language,
            String kind,
            String storageKey,
            boolean autoGenerated
    ) {
    }

    public record VideoProgressDto(
            String videoId,
            String userId,
            int positionSeconds,
            Integer durationSeconds,
            double playbackRate,
            boolean completed,
            Instant updatedAt
    ) {
    }

    public record VideoManifestDto(
            String videoId,
            String protocol,
            String status,
            List<VideoRenditionDto> renditions,
            List<VideoCaptionDto> captions
    ) {
    }

    public record PlaybackUrlDto(
            String videoId,
            String url,
            Instant expiresAt
    ) {
    }

    public record VideoReadinessDto(
            String id,
            String courseId,
            String status,
            boolean usable
    ) {
    }

    // ---- requests ----

    public record RegisterVideoRequestDto(
            String mediaAssetId,
            String courseId,
            @NotBlank String title,
            @NotBlank String sourceStorageKey,
            Integer durationSeconds
    ) {
    }

    public record StartTranscodeRequestDto(
            String requestedBy
    ) {
    }

    public record UpdateProgressRequestDto(
            String userId,
            @NotNull @PositiveOrZero Integer positionSeconds,
            Integer durationSeconds,
            Double playbackRate,
            Boolean completed
    ) {
    }
}
